### PR TITLE
minified file updated

### PR DESCRIPTION
**Pull request by migig**
@lipis I hope this time is okay.

I only ran `grunt uglify` I hope that will do the trick?

### CODE REVIEW

**Comment by lipis** [comment]
thanks..

**Comment by migig** [comment]
@lipis You will include in next update, or push it now? And then I can close the PR and issue.

**Comment by lipis** [comment]
done.. https://github.com/lipis/bootstrap-sweetalert/releases

**Comment by migig** [comment]
:smile:

**Pull request merged**
