### PR TITLE
Make more use of less mixins

### LINKED ISSUE #47: Property 'animation' is not working
I tried the standard SA, and there it is working, but when I use bootstrap-sweetalert, it is ignored. No matter what value I supply, such as 'slide-from-bottom', the modal is popped up with the same exact double pop effect. 

Here is the sources of the entire HTML page: https://gist.github.com/ipolevoy/9dc5955d17cd42d805da

Any help is appreciated!

### PR DESCRIPTION
**Pull request by alekitto**
This simplifies the animation less file (i've also ported two animations i've missed while syncing from sweetalert).

Also, use of [Autoprefixer](https://github.com/postcss/autoprefixer) should be considered to simplify current css

It fixes #47

### CODE REVIEW

**Comment by lipis** [comment]
That was by design..
http://caniuse.com/#feat=transforms2d

**Comment by lipis** [comment]
https://github.com/t4t5/sweetalert/pull/142

**Comment by alekitto** [comment]
Didn't notice that. I've removed `-moz` prefixed rules

**Comment by lipis** [comment]
my point is that we don't really need anybof those.. as they are pretty much supported in out of the box in the latest versions

**Comment by alekitto** [comment]
Thinkin' about this: probably you're right.
Do you think we should remove all the prefixed version of the css rules?
In case someone need to support old browsers can use autoprefixer in its build pipeline

**Comment by lipis** [comment]
Exactly.. we should look forward :D and most of the browsers updating automagically these days.. :)

**Comment by alekitto** [comment]
Ok. I'll open another one to remove prefixed css rules

**Pull request closed without merging**
